[
  {
    id: `xample-id`,
    title: `example-title`,
    description: `example-description`,
    content: `example-content`,
    quotes: [`example-quote`],
    learnedFrom: `example-learnedFrom`,
    usefulResources: [`example-usefulResource`],
    relatedAdvice: [`example-relatedAdvice`],
    topics: [`example-topic`],
    tags: [`example-tag`],
  },
  {
    id: `01-make-your-bed`,
    title: `Make your bed`,
    description: `Completing the first simplest task of the day gives you the confidence to complete the next ones.`,
    content: `Completing the first simplest task of the day gives you the confidence to complete the next ones.`,
    quotes: [`Make your bed`],
    learnedFrom: `The book Make Your Bed: Little Things That Can Change Your Life...And Maybe the World by Admiral William H. McRaven`,
    usefulResources: [`Make Your Bed: Little Things That Can Change Your Life...And Maybe the World by Admiral William H. McRaven`],
    relatedAdvice: [],
    topics: [`Goals`],
    tags: [`goals`, `completing-tasks`, `self-help`],
  },
  {
    id: `02-dry-dont-repeat-yourself`,
    title: `DRY. Don't Repeat Yourself`,
    description: `Every piece of knowledge must have a single, unambiguous, authoritative representation within a system`,
    content: `Don't repeat yourself, Dont do the same thing over an over if it is not necessary.`,
    quotes: [`Don't Repeat Yourself`],
    learnedFrom: `Software Development and in the book The Pragmatic Programmer by Andy Hunt and Dave Thomas.`,
    usefulResources: [`The Pragmatic Programmer by Andy Hunt and Dave Thomas.`],
    relatedAdvice: [],
    topics: [`Time`, `Solutions`, `Growing`],
    tags: [`goals`, `completing-tasks`, `self-help`],
  },
];
// Do not have the same item duplicated maybe related to DRY?
